server:
  port: 8081

spring:
  application.type: angular_2_springboot
  profiles.active: test

logging.level:
  root: INFO
  br.com.embraer.aheadpro: DEBUG
  org.hibernate.orm.deprecation: ERROR

liquibase.change-log: classpath:database/liquibase/db.changelog.xml

---

spring:
  profiles: test
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    show-sql: true

liquibase:
  enabled: true
  contexts: test

---